import 'dart:convert';

import 'package:flutter/services.dart';
import 'package:planespotting/domain/models/planechase_card.dart';

/// Reads the bundled card metadata generated by `tool/fetch_cards.py`.
class CardAssetService {
  CardAssetService({AssetBundle? bundle}) : _bundle = bundle ?? rootBundle;

  final AssetBundle _bundle;

  Future<List<PlanechaseCard>> loadCards() async {
    final raw = await _bundle.loadString('assets/cards.json');
    final decoded = (jsonDecode(raw) as List<dynamic>).cast<Map<String, dynamic>>();
    return decoded.map(PlanechaseCard.fromJson).toList();
  }
}
